docs: 'Park's Quiz 1
junkfood-dev/reviews pull request #50
Opened 2024-09-07 09:49 UTC by SangWon-Lee1

아주아주 간단한 출결 시스템 완료

2024-09-07 12:21 UTC, vivaan-park requested changes
static에 대해서 더 고민해보세요.

2024-09-07 12:21 UTC, vivaan-park commented on sangwon/java/src/_2024_09_07/AttendanceSystem.java
> +    // ArrayList<Date> 제네릭? 뭔지몰라서 찾아봄
안배운건데 잘했음

2024-09-07 12:21 UTC, vivaan-park commented on sangwon/java/src/_2024_09_07/AttendanceSystem.java
> +        Date currentDate = new Date();
이것도 안배운건데 잘했음

2024-09-07 12:21 UTC, vivaan-park commented on sangwon/java/src/_2024_09_07/AttendanceSystem.java
> +    static int id = 202400;
static에 대해서 다시 공부해보세요.

2024-09-07 13:06 UTC, vivaan-park approved these changes

2024-09-07 13:06 UTC, vivaan-park commented on sangwon/java/src/_2024_09_07/AttendanceSystem.java
> +    static int nextId = 202400;
참 잘했어요.
다음부터는 클래스 변수끼리, 인스턴르 변수끼리 나열하면 가독성이 더 좋을 것 같습니다.

2024-09-07 13:08 UTC, SangWon-Lee1 commented on sangwon/java/src/_2024_09_07/AttendanceSystem.java
> +    static int nextId = 202400;
넵 알겠습니다 생선님

2024-09-08 03:11 UTC, ejjeong9103 approved these changes

2024-09-08 03:11 UTC, merged